
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    #data: database/data.sql
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver

  #hibernate.hbm2ddl.auto 参数的作用主要用于：自动创建
  #dialect 主要是指定生成表名的存储引擎为 InnoDBD
  #show-sql 是否打印出自动生成的 SQL，方便调试的时候查看
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.example.admin.config.MySQL5DialectUTF8

  thymeleaf:
    cache: false
    mode: HTML
log:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

info:
  app:
    name: @project.artifactId@
    encode: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
server:
  port: 8000
